name: Add issue or pull request to project board

on:
  workflow_call:

jobs:
  add-to-project:
    name: Add issue or pull request to project
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 1.0.0
      - name: 'Get next minor version'
        id: semvers
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.previoustag.outputs.tag }}
      - name: 'Create new milestone'
        id: createmilestone
        uses: "WyriHaximus/github-action-create-milestone@v1"
        with:
          title: ${{ steps.semvers.outputs.patch }}
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
      - name: Add to project
        uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/users/bitpredator/projects/4
          github-token: ${{ secrets.MY_GITHUB_TOKEN }}
        id: add-project
      - name: Update project fields
        uses: titoportas/update-project-fields@v0.1.0
        with:
          project-url: https://github.com/users/bitpredator/projects/4
          github-token: ${{ secrets.MY_GITHUB_TOKEN }}
          item-id: ${{ steps.add-project.outputs.itemId }}
          field-keys: Date,Priority,ReleaseVersion
          field-values: ${{ env.date }},Unrealised,${{ steps.semvers.outputs.patch }}